### DISCUSSION TITLE
New level files format

### DISCUSSION THREAD

**Discussion by tomangelo2** [colobot/colobot#1809] [General]
Idea: implement level definitions in more robust, flexible format
Goal: increased readability of files, better support for present and future features (like multiple slots, custom objects with custom properties), syntax supported by most text editors, format already well known for people interested in creating user levels.

Current `Scene` format while possible to expand has some limitations. It's syntax is foreign for any text format and most of people who might want to create custom levels, doesn't handle nesting very well. While it's possible to expand it, it might be better to leave it in it's current form for backwards compatibility, and move to new format with all new features.

Current candidates:
- JSON
- YAML
- XML

Feel free to propose other formats if you think they might fit.

JSON is very popular format, its support is already implemented in engine through nlohmann-json library, making implementing it for level files easier.
YAML is less popular, however it aims to be more human-friendly and more feature-rich, including comments and relational anchors (example of their usage below), at the cost of more complex and potentially confusing syntax.
XML is another popular format, also includes some features missing in JSON (schema version, namespaces, more data types). Due to requirement of closing every field, files tend to be heavier.

One feature missing in current format is support for slots in objects. While technically it's possible to add support for it (see discussion under #1748), we could just define whole object nested under slot definition. Example:
```json
{
  "Objects":[
    {"category":"WingedGrabber", "shieldLevel":0.6, "position":"167.5,-92,14", "orientation":"-14", "slots":[
      {"category":"NuclearCell", "energyLevel":0.2},
      {"category":"BlackBox", "shieldLevel":0.9}
      ]
    }
  ]
}
```

This way we can define every detail of the object and objects that are inserted into any slot. 

With YAML relational anchors we could also define object once as an anchor, then use it to create multiple objects with same parameters. Example:
```yaml
# Define common properties of ants
# Also with comments we can leave some description about why we set up some thing this or that way

&ant-common # creating an anchor
category: AlienAnt
program0: 
  file: ant1.cbot
  isRunning: true
program1:
  file: ant2.cbot
  isRunning: false

# Define a group of ants
Objects: 
ant1: 
  position: 121,-14, 16
  <<: *ant-common # this alias will be replaced with our anchor
ant2: 
  position: 125,-16,17
  <<: *ant-common # no need to copy-paste same thing over and over
ant3:
  position: 128,-20,15
 <<: *ant-common # ditto
# Hopefully syntax there is correct, I don't know this format very well.
# Hopefully you get the idea
```
A simple approach to DRY rule, saving level creators time and possible bugs related to updating many objects.
Similar mechanisms can probably be achieved with JSON/XML/other format, YAML just implements it out-of-the-box.

Also since saved games are stored in `Scene` format as well, it should also be replaced with new format to feature parity.

Feel free to share your opinion about that idea.

**Comment by hexagonrecursion** [comment]
I fixed the syntax:
```yaml
TheNameOfThisKeyDoesNotMatter: &ant-common
  category: AlienAnt
  program0: 
    file: ant1.cbot
    isRunning: true
  program1:
    file: ant2.cbot
    isRunning: false

Objects:
  - position: [121,-14, 16]
    <<: *ant-common
  - position: [125,-16,17]
    <<: *ant-common
  - position: [128,-20,15]
    <<: *ant-common
```
